"""add_womens_mode_verification

Revision ID: 495246c762d7
Revises: 0001_initial
Create Date: 2026-05-12 07:55:09.137810
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '495246c762d7'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_womens_mode_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
    # Clean up index if unique state needs adjustment (Alembic autogenerate suggested this)
    try:
        op.drop_index('ix_users_email', table_name='users')
    except Exception:
        pass
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_column('users', 'is_womens_mode_verified')
    # ### end Alembic commands ###
