"""add womens mode relevant to reports

Revision ID: 78be058b7b91
Revises: 495246c762d7
Create Date: 2026-05-13 00:48:32.495737
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '78be058b7b91'
down_revision: Union[str, None] = '495246c762d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('is_womens_mode_relevant', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'is_womens_mode_relevant')
    # ### end Alembic commands ###

